### ISSUE TITLE
"cannot import name ValidationError"

### ISSUE THREAD

**Issue by npanyam** [inveniosoftware/troubleshooting#18]
Hi,

This is probably not really an issue with Invenio. On googling it up I see that same error showing up elsewhere, too. I ran into this error (pasted below) while configuring a fresh instance of invenio-1.2.2 . Platform is CentOS7 and Python 2.7.5 . Is it hitting a version problem? What is the work around? Thanks for any help!

[docrepo@www2 invenio-src]$ /opt/invenio/bin/inveniocfg --load-bibfield-conf
>>> Going to load BibField config...
Traceback (most recent call last):
  File "/opt/invenio/bin/inveniocfg", line 33, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/invenio/inveniocfg.py", line 1718, in main
    cli_cmd_load_bibfield_config(conf)
  File "/usr/lib64/python2.7/site-packages/invenio/inveniocfg.py", line 828, in cli_cmd_load_bibfield_config
    BibFieldParser.reparse()
  File "/usr/lib64/python2.7/site-packages/invenio/bibfield_config_engine.py", line 287, in reparse
    cls()._create()
  File "/usr/lib64/python2.7/site-packages/invenio/bibfield_config_engine.py", line 337, in _create
    self._create_rule(rule)
  File "/usr/lib64/python2.7/site-packages/invenio/bibfield_config_engine.py", line 468, in _create_rule
    self.__create_json_extra(rule)
  File "/usr/lib64/python2.7/site-packages/invenio/bibfield_config_engine.py", line 542, in __create_json_extra
    from invenio.bibfield_utils import CFG_BIBFIELD_FUNCTIONS
  File "/usr/lib64/python2.7/site-packages/invenio/bibfield_utils.py", line 375, in <module>
    from cerberus import ValidationError, SchemaError
ImportError: cannot import name ValidationError

-
Nagaraj

**Comment by egabancho** [comment]
Can you check your version of `cerberus`? This problems rings a bell but I am not completely sure about it.
```
pip freeze | grep -I cerberus
Cerberus==0.5
```

**Comment by npanyam** [comment]
Thanks for the clue! I had Cerberus==1.1. I removed it and installed 0.5 version and that worked!
