### ISSUE TITLE
invenio 2.1, multiple values for keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by Atisom** [inveniosoftware/troubleshooting#27]
Dear Invenio Development Team,

I installed the invenio 2.1 in my Ubuntu 14.04 LTS server. When I try to start the server, I get this error:
```
(invenio) ubuntu@invenio-v2:~/.virtualenvs/invenio/src/invenio$ inveniomanage runserver
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/invenio/bin/inveniomanage", line 11, in <module>
    load_entry_point('invenio', 'console_scripts', 'inveniomanage')()
  File "/home/ubuntu/.virtualenvs/invenio/src/invenio/invenio/base/manage.py", line 103, in main manager.run()
  File "/home/ubuntu/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/ubuntu/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/ubuntu/.virtualenvs/invenio/src/invenio/invenio/ext/script/__init__.py", line 177, in __call__
    res = super(SignalingCommand, self).__call__(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask_script/commands.py", line 479, in __call__**self.server_options)
TypeError: <invenio.ext.script.SignalingCommand object at 0x7fe83d4fe1d0>: run() got multiple values for keyword argument 'ssl_context'
```

How can I solve it?

Thanks,
Attila

**Comment by lnielsen** [comment]
Dear Attila, 

We do not recommend using Invenio v2.1 as the 2.x code base is not suitable for production systems, and will not receive any further development nor security fixes. We are working hard towards getting a final v3 release out as the v1.x code base is also quite aging now.

**Comment by Atisom** [comment]
Dear Inielsen,

Thank you for your reply.

What do you think, when the new release will be available? (in this year, in the first quarter of the next year or later)

**Comment by lnielsen** [comment]
We've just finished the latest Invenio sprint, and we'll need one more sprint to finalise the v3 release, so I estimate we're at mid-February before the V3 release of base, auth and metadata bundles.
Note, this is a release of the framework. It's not a full replacement of all functionality that was available in v1.

**Comment by Atisom** [comment]
Thank you!

Have a nice day!
