### ISSUE TITLE
Invenio-records-rest: AttributeError: 'dict' object has no attribute 'data'

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/troubleshooting#33]
## Problem:
Dictionary does not have attribute data in invenio-records-rest when building response for queries and indexing. See stack trace:
```
127.0.0.1 - - [28/Feb/2018 09:35:09] "GET /api/records/?page=1&size=20&q=test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_rest/views.py", line 253, in dispatch_request
    *args, **kwargs
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_records_rest/views.py", line 540, in get
    item_links_factory=self.item_links_factory,
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_rest/views.py", line 234, in make_response
    return serializer(*args, **kwargs)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_records_rest/serializers/response.py", line 72, in view
    item_links_factory=item_links_factory),
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_records_rest/serializers/json.py", line 86, in serialize_search
    ) for hit in search_result['hits']['hits']],
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_records_rest/serializers/marshmallow.py", line 58, in transform_search_hit
    links_factory=links_factory, **kwargs), context)
  File "/home/ppanero/workspace/virtual_env/ils/lib/python2.7/site-packages/invenio_records_rest/serializers/marshmallow.py", line 45, in dump
    return self.schema_class(context=context).dump(obj).data
AttributeError: 'dict' object has no attribute 'data'
```

## Solution
Install ``marshamallow`` package version lower than 3.0.0b7 (i.e. <=3.0.0b6)

## Why
In the latest version it returns a `dict` instead of a `MarshalResult` and therefore the object does not have a data attribute.

**Comment by jorgeas80** [comment]
Man, you saved my day. My whole week, actually
